---
title: "R Notebook"
output: html_document
---

### URL:https://ggplot2.tidyverse.org/reference/labs.html

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(ggplot2)
library(jsonlite)
library(listviewer)
library(V8)
library(vegawidget)
```

## example1
### ggplot2
```{r}
p <- ggplot(mtcars, aes(mpg, wt, colour = cyl)) + geom_point()+labs(colour = "Cylinders")
  
p
```

### ggspec

```{r}
# ggspec
ggjson<-fromJSON('
{
  "data": {
    "data-00": {
      "metadata": {},
      "observations": [{}, {}]
    }
  },
  "layers": [
    {
      "data": "data-00",
      "geom": {"class": "GeomPoint"},
      "mapping": {
        "x": {"field": "wt", "type": "quantitative"},
        "y": {"field": "mpg", "type": "quantitative"},
        "colour": {"field": "cyl", "type": "quantitative"}
      }
    }
  ],
  "scales": [],
  "labels": {
    "x": "wt",
    "y": "mpg",
    "colour":"Cylinders"
  }
}
')

data<-mtcars

ggjson$data$`data-00`$observations=data

jsonedit(ggjson,mode='code')

ggspec<-toJSON(ggjson,auto_unbox=TRUE)

write(ggspec,'test.json')
```

### vega-lite
```{r}

# V8
ct <- v8()

ct$source("js/compile.js")

ct$assign("ggspec", ggspec)

ct$assign("ggspec",JS("JSON.parse(ggspec)"))

vlspec<-ct$get(JS("ggvega.gg2vl(ggspec)"))

as_vegaspec(vlspec)

```

## example 2
### ggplot2

```{r}
p <- ggplot(mtcars, aes(mpg, wt, colour = cyl)) + geom_point()+
  labs(x = "New x label")
  
p
```
### ggspec

```{r}
# ggspec
ggjson<-fromJSON('
{
  "data": {
    "data-00": {
      "metadata": {},
      "observations": [{}, {}]
    }
  },
  "layers": [
    {
      "data": "data-00",
      "geom": {"class": "GeomPoint"},
      "mapping": {
        "x": {"field": "wt", "type": "quantitative"},
        "y": {"field": "mpg", "type": "quantitative"},
        "colour": {"field": "cyl", "type": "quantitative"}
      }
    }
  ],
  "scales": [],
  "labels": {
    "x": "New x label",
    "y": "mpg",
    "colour":"cyl"
  }
}
')

data<-mtcars

ggjson$data$`data-00`$observations=data

jsonedit(ggjson,mode='code')

ggspec<-toJSON(ggjson,auto_unbox=TRUE)

write(ggspec,'test.json')
```

### vega-lite
```{r}
# V8
ct <- v8()

ct$source("js/compile.js")

ct$assign("ggspec", ggspec)

ct$assign("ggspec",JS("JSON.parse(ggspec)"))

vlspec<-ct$get(JS("ggvega.gg2vl(ggspec)"))

as_vegaspec(vlspec)
```

## example 3
### ggplot2

```{r}
p <- ggplot(mtcars, aes(mpg, wt, colour = cyl)) + geom_point()+
  labs(title = "New plot title")  
p
```
### ggspec

```{r}
# ggspec
ggjson<-fromJSON('
{
  "data": {
    "data-00": {
      "metadata": {},
      "observations": [{}, {}]
    }
  },
  "layers": [
    {
      "data": "data-00",
      "geom": {"class": "GeomPoint"},
      "mapping": {
        "x": {"field": "wt", "type": "quantitative"},
        "y": {"field": "mpg", "type": "quantitative"},
        "colour": {"field": "cyl", "type": "quantitative"}
      }
    }
  ],
  "scales": [],
  "labels": {
    "x": "wt",
    "y": "mpg",
    "colour":"cyl",
    "title":"New plot title"
  }
}
')

data<-mtcars

ggjson$data$`data-00`$observations=data

jsonedit(ggjson,mode='code')

ggspec<-toJSON(ggjson,auto_unbox=TRUE)

write(ggspec,'test.json')
```

### vega-lite
```{r}
# V8
ct <- v8()

ct$source("js/compile.js")

ct$assign("ggspec", ggspec)

ct$assign("ggspec",JS("JSON.parse(ggspec)"))

vlspec<-ct$get(JS("ggvega.gg2vl(ggspec)"))

as_vegaspec(vlspec)
```




## example 4
### ggplot2

```{r}
p <- ggplot(mtcars, aes(mpg, wt, colour = cyl)) + geom_point()+
  labs(title = "New plot title", subtitle = "A subtitle")
p
p <- ggplot(mtcars, aes(mpg, wt, colour = cyl)) + geom_point()+
  labs(caption = "(based on data from ...)")

p
p <- ggplot(mtcars, aes(mpg, wt, colour = cyl)) + geom_point()+
  labs(title = "title", tag = "A")
p
p <- ggplot(mtcars, aes(mpg, wt, colour = cyl)) + geom_point()+
  labs(title = "title") + labs(title = NULL)
p
```
### ggspec

```{r}
# ggspec
ggjson<-fromJSON('
{
  "data": {
    "data-00": {
      "metadata": {},
      "observations": [{}, {}]
    }
  },
  "layers": [
    {
      "data": "data-00",
      "geom": {"class": "GeomPoint"},
      "mapping": {
        "x": {"field": "wt", "type": "quantitative"},
        "y": {"field": "mpg", "type": "quantitative"},
        "colour": {"field": "cyl", "type": "quantitative"}
      }
    }
  ],
  "scales": [],
  "labels": {
    "x": "wt",
    "y": "mpg",
    "colour":"cyl",
    "title":null
  }
}
')

data<-mtcars

ggjson$data$`data-00`$observations=data

jsonedit(ggjson,mode='code')

ggspec<-toJSON(ggjson,auto_unbox=TRUE)

write(ggspec,'test.json')
```

### vega-lite
Maybe use column
```{r}
# V8
ct <- v8()

ct$source("js/compile.js")

ct$assign("ggspec", ggspec)

ct$assign("ggspec",JS("JSON.parse(ggspec)"))

vlspec<-ct$get(JS("ggvega.gg2vl(ggspec)"))

as_vegaspec(vlspec)
```






















